<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDnja7wg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDnja7wg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDnja7wg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDnja7wg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDnja7wg\appDevDebugProjectContainer([
    'container.build_hash' => 'Dnja7wg',
    'container.build_id' => 'cb10da36',
    'container.build_time' => 1564064473,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDnja7wg');
